services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: fuel_test
      MYSQL_USER: fuel_app
      MYSQL_PASSWORD: super_secret_password
