name: CI

on: [push]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: fuel_test
          MYSQL_USER: fuel_app
          MYSQL_PASSWORD: super_secret_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Set up locale
      run: |
        sudo apt-get update
        sudo apt-get install -y locales-all

    - name: Check system locale
      run: locale

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        coverage: xdebug

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Apply patch
      run: patch -p1 < a.patch

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h"127.0.0.1" --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Run test suite
      env:
        DB_HOST: 127.0.0.1
      run: fuel/vendor/bin/phpunit -c fuel/core/phpunit.xml --group Core --coverage-html coverage

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        path: coverage
